#!/usr/bin/env bash
set -e

# ─── Grizzly Install Script ───────────────────────────────────────────────────
# Usage:
#   sudo bash -c "$(curl -sL https://raw.githubusercontent.com/Grizzly-xray/Grizzly/main/scripts/install.sh)"
#   sudo bash -c "$(curl -sL ...)" @ install --domain yourdomain.com
# ─────────────────────────────────────────────────────────────────────────────

REPO="https://github.com/Grizzly-xray/Grizzly"
RAW="https://raw.githubusercontent.com/Grizzly-xray/Grizzly/main"
INSTALL_DIR="/opt/grizzly"
DATA_DIR="/var/lib/grizzly"
BIN="/usr/local/bin/grizzly"
BOLD="\033[1m"
GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
CYAN="\033[0;36m"
RESET="\033[0m"

# ─── Args ─────────────────────────────────────────────────────────────────────
COMMAND="${1:-install}"
DOMAIN=""
for arg in "$@"; do
  case $arg in
    --domain=*) DOMAIN="${arg#*=}" ;;
    --domain)   shift; DOMAIN="$1" ;;
  esac
done

# ─── Helpers ──────────────────────────────────────────────────────────────────
log()     { echo -e "${GREEN}[✓]${RESET} $1"; }
info()    { echo -e "${CYAN}[•]${RESET} $1"; }
warn()    { echo -e "${YELLOW}[!]${RESET} $1"; }
error()   { echo -e "${RED}[✗]${RESET} $1"; exit 1; }
divider() { echo -e "\n${CYAN}────────────────────────────────────────${RESET}"; }

check_root() {
  [[ $EUID -ne 0 ]] && error "Please run as root: sudo bash install.sh"
}

check_os() {
  . /etc/os-release 2>/dev/null || true
  if [[ "$ID" != "ubuntu" && "$ID" != "debian" ]]; then
    warn "OS '$ID' not officially supported. Proceeding anyway..."
  fi
  log "OS: $PRETTY_NAME"
}

install_docker() {
  if command -v docker &>/dev/null; then
    log "Docker already installed ($(docker --version))"
    return
  fi
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | bash
  systemctl enable docker
  systemctl start docker
  log "Docker installed"
}

install_docker_compose() {
  if docker compose version &>/dev/null 2>&1; then
    log "Docker Compose already available"
    return
  fi
  info "Installing Docker Compose plugin..."
  apt-get install -y docker-compose-plugin &>/dev/null
  log "Docker Compose installed"
}

download_grizzly() {
  info "Downloading Grizzly to $INSTALL_DIR..."
  mkdir -p "$INSTALL_DIR" "$DATA_DIR"

  if command -v git &>/dev/null; then
    if [[ -d "$INSTALL_DIR/.git" ]]; then
      git -C "$INSTALL_DIR" pull --quiet
    else
      git clone --quiet --depth=1 "$REPO" "$INSTALL_DIR"
    fi
  else
    apt-get install -y git &>/dev/null
    git clone --quiet --depth=1 "$REPO" "$INSTALL_DIR"
  fi
  log "Grizzly downloaded"
}

generate_secret() {
  python3 -c "import secrets; print(secrets.token_urlsafe(48))" 2>/dev/null \
    || openssl rand -hex 48
}

setup_env() {
  local env_file="$INSTALL_DIR/panel/.env"

  if [[ -f "$env_file" ]]; then
    warn ".env already exists — skipping generation (delete to regenerate)"
    return
  fi

  info "Generating configuration..."

  local secret_key
  secret_key=$(generate_secret)

  local db_password
  db_password=$(generate_secret | head -c 24)

  local sub_prefix="http://$(curl -s ifconfig.me 2>/dev/null || echo 'YOUR_IP'):8000"
  [[ -n "$DOMAIN" ]] && sub_prefix="https://$DOMAIN"

  cat > "$env_file" << EOF
# ── Grizzly Configuration ──────────────────────────────────────────────────
# Generated by install script — $(date)

# Database
DATABASE_URL=postgresql+asyncpg://grizzly:${db_password}@postgres/grizzlydb

# Security
SECRET_KEY=${secret_key}
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# NATS
NATS_URL=nats://nats:4222

# Redis
REDIS_URL=redis://redis:6379

# Subscription URL
SUBSCRIPTION_URL_PREFIX=${sub_prefix}

# Health monitoring (seconds before alert)
NODE_HEARTBEAT_TIMEOUT=300
NODE_STATS_TIMEOUT=300

# Telegram alerts (optional — fill in to enable)
TELEGRAM_BOT_TOKEN=
TELEGRAM_ADMIN_IDS=[]

DEBUG=false
EOF

  # Also write db password to docker-compose override
  cat > "$INSTALL_DIR/docker-compose.override.yml" << EOF
version: "3.9"
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: grizzly
      POSTGRES_DB: grizzlydb
EOF

  log "Configuration generated"
}

install_cli() {
  info "Installing grizzly CLI..."
  cat > "$BIN" << 'CLIEOF'
#!/usr/bin/env bash
# Grizzly CLI
DIR="/opt/grizzly"
cd "$DIR" || exit 1

case "$1" in
  start)     docker compose up -d && echo "Grizzly started ✅" ;;
  stop)      docker compose down && echo "Grizzly stopped" ;;
  restart)   docker compose restart && echo "Grizzly restarted ✅" ;;
  status)    docker compose ps ;;
  logs)      docker compose logs -f --tail=100 "${2:-panel}" ;;
  update)
    git pull --quiet
    docker compose pull
    docker compose up -d
    echo "Grizzly updated ✅"
    ;;
  backup)
    TS=$(date +%Y%m%d_%H%M%S)
    BACKUP="/var/lib/grizzly/backup_${TS}.tar.gz"
    tar -czf "$BACKUP" /var/lib/grizzly/postgres_data /opt/grizzly/panel/.env 2>/dev/null
    echo "Backup saved: $BACKUP"
    ;;
  admin)
    shift
    docker compose exec panel python -c "
import asyncio, sys
from app.core.database import AsyncSessionLocal
from app.core.security import hash_password
from app.models.admin import Admin, AdminRole

async def run():
    args = sys.argv[1:]
    if 'create' in args:
        role = AdminRole.sudo if '--sudo' in args else AdminRole.admin
        username = input('Username: ')
        password = input('Password: ')
        async with AsyncSessionLocal() as db:
            a = Admin(username=username, hashed_password=hash_password(password), role=role)
            db.add(a)
            await db.commit()
            print(f'Admin \"{username}\" created with role={role.value} ✅')
asyncio.run(run())
" "$@"
    ;;
  *)
    echo "Usage: grizzly [start|stop|restart|status|logs|update|backup|admin]"
    echo ""
    echo "  start          Start all services"
    echo "  stop           Stop all services"
    echo "  restart        Restart all services"
    echo "  status         Show service status"
    echo "  logs [svc]     Show logs (default: panel)"
    echo "  update         Pull latest and restart"
    echo "  backup         Backup database and config"
    echo "  admin create   Create a new admin"
    echo "  admin create --sudo  Create sudo admin"
    ;;
esac
CLIEOF

  chmod +x "$BIN"
  log "CLI installed at $BIN"
}

start_services() {
  info "Starting Grizzly services..."
  cd "$INSTALL_DIR"
  docker compose pull --quiet
  docker compose up -d
  log "Services started"
}

wait_for_panel() {
  info "Waiting for panel to be ready..."
  local max=30
  for i in $(seq 1 $max); do
    if curl -sf "http://localhost:8000/api/health" &>/dev/null; then
      log "Panel is ready"
      return
    fi
    sleep 2
    echo -n "."
  done
  warn "Panel didn't respond in time — check: grizzly logs"
}

print_summary() {
  local ip
  ip=$(curl -s ifconfig.me 2>/dev/null || echo "YOUR_IP")
  [[ -n "$DOMAIN" ]] && ip="$DOMAIN"

  divider
  echo -e "\n${BOLD}${GREEN}🐻 Grizzly installed successfully!${RESET}\n"
  echo -e "  Dashboard:    ${CYAN}http://${ip}:3000${RESET}"
  echo -e "  API Docs:     ${CYAN}http://${ip}:8000/api/docs${RESET}"
  echo ""
  echo -e "  ${BOLD}Next step — create your first admin:${RESET}"
  echo -e "  ${YELLOW}grizzly admin create --sudo${RESET}"
  echo ""
  echo -e "  ${BOLD}Useful commands:${RESET}"
  echo -e "  grizzly status    — view services"
  echo -e "  grizzly logs      — view logs"
  echo -e "  grizzly update    — update to latest"
  divider
  echo ""
}

# ─── Main ─────────────────────────────────────────────────────────────────────
main() {
  clear
  echo -e "${BOLD}${CYAN}"
  cat << 'LOGO'
   ____       _                _
  / ___|_ __ (_)__________ _  | |_   _
 | |  _| '__| |_  /_  / _` | | | | | |
 | |_| | |  | |/ / / / (_| | | | |_| |
  \____|_|  |_/___/___\__,_| |_|\__, |
                                  |___/
LOGO
  echo -e "${RESET}"

  check_root
  check_os
  divider

  case "$COMMAND" in
    install)
      info "Starting installation..."
      install_docker
      install_docker_compose
      download_grizzly
      setup_env
      install_cli
      start_services
      wait_for_panel
      print_summary
      ;;
    *)
      error "Unknown command: $COMMAND"
      ;;
  esac
}

main "$@"
